### ISSUE TITLE
Vat universal RP Question

### ISSUE THREAD

**Issue by VoxelStudio** [keijiro/HdrpVatExample#10]
Great job!
You open up a huge field of possibilities.
I admit that I looked at the universal RP approach a lot, but I failed to obtain a result.
would you have tracks to convert the VFX graph and the shader graph to universal RP format for android development?
 sorry if the question has already been asked but I admit that I have not found any answer

Thanks again for your great work.

**Comment by keijiro** [comment]
I pushed Universal Render Pipeline examples to the `urp` branch.

https://github.com/keijiro/HdrpVatExample/tree/urp

I just replaced master nodes in the shader graphs. I also had to replace Lit Mesh Output context in the VFX graph with (Unlit) Mesh Output because VFX Graph doesn't support Lit outputs on URP at the moment.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further problems.
